site_name: Сайт-тест Вячеслава
site_url: https://Vjacheslav772.github.io/Test_Site/
theme:
  name: material
  #шрифты для текста и сылок:
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  #logo: assets/logo.png
  icon:
    logo: fontawesome/solid/w
  #favicon: assets/favicon.ico
  #favicon: fonta
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

site_author: Viacheslav Aprodu
copyright: Copyright &copy; 2025 Viacheslav Aprodu
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences