
site_name: Vyacheslav Aprodu — PLC & SCADA Engineer-Developer | Siemens Automation Expert
site_url: https://Vjacheslav772.github.io/Test_Site/
site_author: Vyacheslav Aprodu
site_description: Персональный саffffffffйт инженера-программиста контроллеров Siemens SIMATIC

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

# ВАЖНО: extra_css должен быть на корневом уровне, НЕ внутри theme!
extra_css:
  - assets/css/extra.css

nav:
  - Главная: index.md
  - О себе:
      - Основное: about/index.md
      - Опыт работы: about/experience.md
      - Навыки и компетенции: about/skills.md
  - Портфолио:
      - Главная: portfolio/index.md
      - Проекты Siemens: portfolio/siemens-projects.md
      - Преподавание: portfolio/teaching.md
      - DevOps проекты: portfolio/devops-projects.md
      - Python разработка: portfolio/python-projects.md
  - Резюме: resume/index.md
  - Блог: blog/index.md
  - Контакты: contacts.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2025 Vyacheslav Aprodu
