site_name: Вячеслав Фамилия - DevOps Engineer & SCADA Developer
site_url: https://Vjacheslav772.github.io/Test_Site/
site_author: Вячеслав
site_description: Персональное портфолио инженера-программиста контроллеров Siemens, DevOps специалиста и преподавателя

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
        
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Главная: index.md
  - Об авторе:
    - Основное: about/index.md
    - Опыт работы: about/experience.md
    - Навыки и компетенции: about/skills.md
  - Портфолио:
    - portfolio/index.md
    - Проекты Siemens: portfolio/siemens-projects.md
    - Преподавание: portfolio/teaching.md
    - DevOps проекты: portfolio/devops-projects.md
    - Python разработка: portfolio/python-projects.md
  - Резюме: resume/index.md
  - Блог: blog/index.md
  - Контакты: contacts.md
site_author: Viacheslav Фамилия
copyright: Copyright &copy; 2025 Viacheslav Фамилия
