site_name: Italianc Mkdocs demo
site_url: https://Vjacheslav772.github.io/Test_Site/
theme:
  name: material
site_author: Viacheslav Aprodu
copyright: Viacheslav Aprodu, 2025
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences